name: amar_karigor
version: 1.0.0+1
publish_to: none
description: Amar Karigor.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.0.0
  http: ^0.13.0
  salomon_bottom_bar: ^3.1.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  shared_preferences: ^2.0.0
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  syncfusion_flutter_sliders: ^19.4.40
  table_calendar: ^3.0.3
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.1  

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/


