name: amar_karigor
version: 1.0.0+1
publish_to: none
description: Amar Karigor.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.0.0
  http: ^0.13.0
  salomon_bottom_bar: ^3.1.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  shared_preferences: ^2.0.0
  shimmer: ^2.0.0
  flutter_native_splash: ^0.1.4 
  flutter_web_plugins:
    sdk: flutter
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
flutter_native_splash:
  image: assets/icons/app_icon.png
  color: ffffff    

